CREATE TABLE users
(
  id BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
  login VARCHAR(32) UNIQUE NOT NULL,
  emial VARCHAR(64) UNIQUE NOT NULL,
  password VARCHAR(32) NOT NULL,
  PRIMARY KEY (id)
)